Repository Administrate/surveymonkey, pull requests merged in 2018-05, with the labels that each got.

#35 Update base manager to take access url
  surveymonkey/constants.py
  surveymonkey/manager.py
  surveymonkey/surveymonkey.py
  surveymonkey/tests/test_base_manager.py
Labels: code-complete

#37 Pt157627343 fix survey monkey integration for customers whose account needs them to access a different api url
  setup.py
  surveymonkey/constants.py
  surveymonkey/manager.py
  surveymonkey/surveymonkey.py
  surveymonkey/tests/test_surveymonkey_connection.py
Labels: calcium, code-complete, nickel

#38 Revert "Pt157627343 fix survey monkey integration for customers whose account needs them to access a different api url"
  setup.py
  surveymonkey/constants.py
  surveymonkey/manager.py
  surveymonkey/surveymonkey.py
  surveymonkey/tests/test_surveymonkey_connection.py
Labels: calcium, nickel

#39 Pt157627343 fix survey monkey integration for customers whose account needs them to access a different api url new branch
  setup.cfg
  setup.py
  surveymonkey/__init__.py
  surveymonkey/constants.py
  surveymonkey/manager.py
  surveymonkey/surveymonkey.py
  surveymonkey/tests/test_surveymonkey_connection.py
Labels: calcium, code-complete, nickel
